### ISSUE TITLE
Problems packaging PyQt5 app for iOS

### ISSUE THREAD

**Issue by GenevieveBuckley** [GenevieveBuckley/hellopyqt#1]
PyQt5 says it supports iOS: https://doc.qt.io/qt-5/ios.html

But I can't get the app to open in the IOS simulator using "briefcase run". It gets clicked/launched and then crashes immediately.

Version numbers:
* XCode Version 11.5 (11E608c)
* python 3.7
* PyQt5 5.14.2
* briefcase 0.3.0

**Comment by GenevieveBuckley** [comment]
XCode console output:

```
2020-05-24 14:25:01.161509+1000 hellopyqt[26938:312067] PythonHome is: /Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Python
2020-05-24 14:25:01.165901+1000 hellopyqt[26938:312067] PYTHONPATH is: PYTHONPATH=/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Application Support/com.example.hellopyqt/app:/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Application Support/com.example.hellopyqt/app_packages
2020-05-24 14:25:01.166198+1000 hellopyqt[26938:312067] Initializing Python runtime...
2020-05-24 14:25:01.546806+1000 hellopyqt[26938:312067] Installing Python NSLog handler...
2020-05-24 14:25:01.887055+1000 hellopyqt[26938:312067] Running 'hellopyqt'...
2020-05-24 14:25:01.979997+1000 hellopyqt[26938:312067] Application quit abnormally!
2020-05-24 14:25:01.980472+1000 hellopyqt[26938:312067] Traceback (most recent call last):
2020-05-24 14:25:01.980810+1000 hellopyqt[26938:312067]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Python/lib/python37.zip/runpy.py", line 193, in _run_module_as_main
2020-05-24 14:25:01.981659+1000 hellopyqt[26938:312067]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Python/lib/python37.zip/runpy.py", line 85, in _run_code
2020-05-24 14:25:01.982485+1000 hellopyqt[26938:312067]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Application Support/com.example.hellopyqt/app/hellopyqt/__main__.py", line 1, in <module>
2020-05-24 14:25:01.983506+1000 hellopyqt[26938:312067]     from hellopyqt.app import main
2020-05-24 14:25:01.983874+1000 hellopyqt[26938:312067]   File "/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Application Support/com.example.hellopyqt/app/hellopyqt/app.py", line 5, in <module>
2020-05-24 14:25:01.986984+1000 hellopyqt[26938:312067]     from PyQt5 import QtCore, QtWidgets
2020-05-24 14:25:01.987387+1000 hellopyqt[26938:312067] ImportError: cannot import name 'QtCore' from 'PyQt5' (/Users/genevieve/Library/Developer/CoreSimulator/Devices/2E9A1427-B607-4F77-94D8-5589ED71BA3D/data/Containers/Bundle/Application/FA0FEB73-DFC8-46EC-B585-13D84331BD95/hellopyqt.app/Library/Application Support/com.example.hellopyqt/app_packages/PyQt5/__init__.py)
2020-05-24 14:25:02.078476+1000 hellopyqt[26938:312067] *** Assertion failure in void _UIApplicationMainPreparations(int, char **, NSString *__strong, NSString *__strong)(), /Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3920.31.100/UIApplication.m:4765
2020-05-24 14:25:02.080141+1000 hellopyqt[26938:312067] Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.
2020-05-24 14:25:02.094082+1000 hellopyqt[26938:312067] Leaving...

```

**Comment by GenevieveBuckley** [comment]
Russell also left this helpful comment on the [beeware/general Gitter](https://gitter.im/beeware/general):

> One piece of the puzzle that might be helpful in your PySide bughunt; the Briefcase template for iOS assumes (a) that myapp is an executable module, and (b) executing that module will cause the creation of an ObjectiveC object called PythonAppDelegate
(The AppDelegate is iOS’s controller for the app lifecycle)
> That is almost certainly not what PySide/PyQt is creating - no idea what a Qt “iOS app” looks like.
> (from a running code perspective, that is)
